module.exports = {
  trailingComma: "all",
  semi: false,
  singleQuote: true,
  printWidth: 100,
  arrowParens: "avoid",
  pugSingleQuote: false,
  pugAttributeSeparator: "none",
  vueIndentScriptAndStyle: false,
  pugSortAttributesBeginning: [
    "^ref$",
    "^v-else$",
    "^v-for$",
    "^:key$",
    "^v-if$",
    "^v-else-if$",
    "^v-on$",
    "^v-bind$",
    "^:",
  ],
  pugSortAttributesEnd: ["^v-model", "^@", "^[a-zA-Z]"],
  pugSortAttributes: "asc",
  pugFramework: "vue",
  pugIdNotation: "literal",
};
